name: poseup
description: 스마트 알람과 AI 포즈 인증이 결합된 PoseUp Flutter 앱 기본 프로젝트
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  go_router: ^14.2.0
  intl: ^0.19.0
  lottie: ^3.1.2
  camera: ^0.11.0+1
  google_mlkit_pose_detection: ^0.10.0
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.1
  cloud_functions: ^5.1.1
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.4
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.3.2
  timezone: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

